### PR TITLE
NoMinuteHand

### PR DESCRIPTION
**Pull request by cooknl**
Wanted a single hand, the hour hand, so went in and commented out and deleted from xml mentions of drawing minute hand

### CODE REVIEW

**Comment by xxv** [comment]
Hello! Thanks for your contribution. Unfortunately, I can't accept this patch.

While this certainly does get rid of the minute hand, there are plenty of people who want it (myself included). Obviously, you're more than welcome to build your own copy of the app using this source tree (even publish it on Play!), but I can't merge these changes upstream.

For me to accept a patch for this feature, a proper solution would be one that adds UI controls to toggle the hands on/off. This is particularly complicated as there presently are no user-configurable options.

My present plans are to create a theming system so people could create no hands, 24-at-the-top, more colorful faces, etc. I've got some rough sketches of ideas for that if you're at all interested.

**Comment by cooknl** [comment]
Copy all! Guess I'll learn how to compile / publish an app!

**Comment by xxv** [comment]
One other small pro-tip: instead of commenting out the code and committing that, just remove the lines. They'll be there stored in git if you ever need to get to them again.

**Comment by cooknl** [comment]
Thx

**Pull request closed without merging**
